matrix: mult_matriz.c
	gcc -Wall mult_matriz.c -o mult_matriz  -fopenmp
	./mult_matriz

diretivas: diretivas.c
	gcc -Wall diretivas.c -o diretivas -fopenmp
	./diretivas

for: for.c
	gcc -Wall for.c -o for -fopenmp
	./for

sections: sections.c
	gcc -Wall sections.c -o sections -fopenmp
	./sections